    version: 1.2
    workflows:
        - subclass:  WDL
          primaryDescriptorPath: /workflows/clinvar/get_clinvar_variants.wdl
          authors:
              - name: Allison Cheney
                email: archeney@ucsc.edu

