    version: 1.2
    workflows:
        - subclass:  WDL
          primaryDescriptorPath: /workflows/combined_gnomad_clinvar/variant_workflow.wdl
          authors:
              - name: Allison Cheney
                email: archeney@ucsc.edu

