version: 1.2
workflows:
    - name: annotate_functional_variants
      subclass:  WDL
      primaryDescriptorPath: /workflows/combined_gnomad_clinvar/variant_workflow.wdl
      authors:
          - name: Allison Cheney
            email: archeney@ucsc.edu
    - name: merge_clinical_data
      subclass:  WDL
      primaryDescriptorPath: /workflows/combined_gnomad_clinvar/merge_clinical_data.wdl
      authors:
          - name: Allison Cheney
            email: archeney@ucsc.edu
    - name: get_gnomad_variants
      subclass: WDL
      primaryDescriptorPath: /workflows/combined_gnomad_clinvar/get_gnomad_vars.wdl
      authors:
          - name : Allison Cheney
            email: archeney@ucsc.edu
    - name: get_clinvar_variants
      subclass: WDL
      primaryDescriptorPath: /workflows/combined_gnomad_clinvar/get_clinvar_variants.wdl
      authors:
          name: Allison Cheney
          email: archeney@ucsc.edu
