include required(classpath("application"))

backend {
  default = Local

  providers {
    Local {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
      config {
        run-in-background = true

        submit = "/usr/bin/env bash ${script}"

        submit-docker = """
        docker run \
          --rm -i \
          ${"--user " + docker_user} \
          --entrypoint ${job_shell} \
          -v ${cwd}:${docker_cwd} \
          ${docker} ${docker_cwd}/execution/script
        """

        root = "cromwell-executions"
        dockerRoot = "/cromwell-executions"

        filesystems {
          local {
            localization: ["hard-link", "soft-link", "copy"]
            caching {
              duplication-strategy: ["hard-link", "soft-link", "copy"]
              hashing-strategy: "md5"
              check-sibling-md5: false
            }
          }
        }

        default-runtime-attributes {
          failOnStderr: false
          continueOnReturnCode: 0
        }
      }
    }
  }
}

call-caching {
  enabled = false
}

database {
  profile = "slick.jdbc.HsqldbProfile$"
  db {
    driver = "org.hsqldb.jdbcDriver"
    url = "jdbc:hsqldb:mem:cromwell-test;shutdown=false;hsqldb.tx=mvcc"
    connectionTimeout = 3000
  }
}
