include required(classpath("application"))

backend {
  default = "Local"
  providers {
    Local {
      actor-factory = "cromwell.backend.impl.local.LocalBackendActorFactory"
      config {
        runtime-attributes = """
          String docker
        """
        submit = "/bin/bash ${script}"
        submit-docker = """
          docker run --rm -i \
            -v ${cwd}:${docker_cwd} \
            -e HOME=${docker_cwd} \
            ${docker} \
            /bin/bash ${docker_script}
        """
      }
    }
  }
}

database {
  profile = "slick.jdbc.HsqldbProfile$"
  db {
    driver = "org.hsqldb.jdbcDriver"
    url = "jdbc:hsqldb:mem:cromwell-test;shutdown=false;hsqldb.tx=mvcc"
    connectionTimeout = 1000
  }
}
