version 1.0

workflow merge_clinical_data {

    meta {
        author: "Allison Cheney"
        email: "archeney@ucsc.edu"
        description: "Add user-supplied clinical data files to gnomad and clinvar variant data using local VRS computation (no network calls)"
    }

    parameter_meta {
        GENE_NAME: "Name of relevant gene"
        VARIANTS_FILE: "The gnomad and clinvar calibration variants file generated by previous workflows."
        FUNCTIONAL_SCORES: "File with functional assay scores VCF or HGVS cDNA or HGVS genomic variant names"
        CLINICAL_DATA: "File with user-supplied case data and VCF or HGVS cDNA or HGVS genomic variant names"
    }
    input {
        String GENE_NAME
        File VARIANTS_FILE
        File FUNCTIONAL_SCORES
        File CLINICAL_DATA
        String VARIANT_TYPE = "gnomad"
    }

    # Compute VRS digests for each input file using local Docker image (no network)
    call compute_vrs_for_variants as vrs_variants {
        input:
            variants_file=VARIANTS_FILE,
            variant_type=VARIANT_TYPE,
            output_name="variants_with_vrs.csv"
    }

    call compute_vrs_for_variants as vrs_scores {
        input:
            variants_file=FUNCTIONAL_SCORES,
            variant_type="functional_assay",
            output_name="functional_scores_with_vrs.csv"
    }

    call compute_vrs_for_variants as vrs_clinical {
        input:
            variants_file=CLINICAL_DATA,
            variant_type="clinical",
            output_name="clinical_data_with_vrs.csv"
    }

    # Merge the VRS-annotated files
    call merge_vrs_files {
        input:
            gene_name=GENE_NAME,
            variants_file=vrs_variants.output_file,
            functional_scores_file=vrs_scores.output_file,
            clinical_data_file=vrs_clinical.output_file
    }

    output {
        File output_combined_variants_file = merge_vrs_files.output_file
    }
}


task compute_vrs_for_variants {
    input {
        File variants_file
        String variant_type
        String output_name
        String docker_image = "brcachallenge/cerfac:vrs-offline-complete"
        Int mem_gb = 4
        Int cpu = 2
        Int disk_gb = 100
    }

    command <<<
        set -eux -o pipefail

        # Run VRS computation using local Docker image
        docker run --rm \
            -v ~{variants_file}:/input/variants.csv:ro \
            -v /tmp:/tmp \
            ~{docker_image} \
            --input /input/variants.csv \
            --output /tmp/~{output_name} \
            --variant-type ~{variant_type}

        # Copy output back
        cp /tmp/~{output_name} .
    >>>

    output {
        File output_file = output_name
    }

    runtime {
        docker: "docker:latest"
        memory: mem_gb + " GB"
        cpu: cpu
        disks: "local-disk " + disk_gb + " HDD"
    }
}


task merge_vrs_files {
    input {
        String gene_name
        File variants_file
        File functional_scores_file
        File clinical_data_file
        Int mem_gb = 8
        Int cpu = 2
        Int disk_gb = 100
    }

    command <<<
        python3 << 'MERGE_CODE'
        import pandas as pd
        import sys

        # Read all three VRS-annotated files
        variants_df = pd.read_csv("~{variants_file}")
        scores_df = pd.read_csv("~{functional_scores_file}")
        clinical_df = pd.read_csv("~{clinical_data_file}")

        # Merge on VRS ID columns
        # The VRS computation adds: vrs_id, vrs_digest, genomic_hgvs, vrs_start, vrs_end, vrs_error
        merged = variants_df.copy()

        # Merge functional scores
        if 'vrs_id' in scores_df.columns:
            merge_cols = ['vrs_id']
            if 'vrs_id' in merged.columns:
                scores_subset = scores_df[[col for col in scores_df.columns if col.startswith(('functional', 'assay', 'score')) or col == 'vrs_id']]
                merged = merged.merge(scores_subset, on='vrs_id', how='left')

        # Merge clinical data
        if 'vrs_id' in clinical_df.columns:
            if 'vrs_id' in merged.columns:
                clinical_subset = clinical_df[[col for col in clinical_df.columns if col.startswith(('case', 'control', 'clinical')) or col == 'vrs_id']]
                merged = merged.merge(clinical_subset, on='vrs_id', how='left')

        # Write output
        merged.to_csv("~{gene_name}_variants_functional_clinical.csv", index=False)
        print(f"Merged {len(merged)} variants with VRS digests")
        print(f"Output: ~{gene_name}_variants_functional_clinical.csv")

        MERGE_CODE
    >>>

    output {
        File output_file = gene_name + "_variants_functional_clinical.csv"
    }

    runtime {
        docker: "python:3.11"
        memory: mem_gb + " GB"
        cpu: cpu
        disks: "local-disk " + disk_gb + " HDD"
    }
}
