version 1.0

workflow merge_clinical_data {

    meta {
        author: "Allison Cheney"
        email: "archeney@ucsc.edu"
        description: "Add user-supplied clinical data files to gnomad and clinvar variant data"
    }

    parameter_meta {
        GENE_NAME: "Name of relevant gene"
        VARIANTS_FILE: "The gnomad and clinvar calibration variants file generated by previous workflows."
        FUNCTIONAL_SCORES: "File with functional assay scores VCF or HGVS cDNA or HGVS genomic variant names"
        CLINICAL_DATA: "File with user-supplied case data and VCF or HGVS cDNA or HGVS genomic variant names"
    }
    input {
        String GENE_NAME
        File VARIANTS_FILE
        File FUNCTIONAL_SCORES
        File CLINICAL_DATA
    }
    #The order in which the workflow block and task definitions are arranged in the script does not matter. 
    #Nor does the order of the call statements matter, as we'll see further on.

    call merge_variants_clinical{
        input: 
            GENE_NAME=GENE_NAME,
            VARIANTS_FILE=VARIANTS_FILE, 
            FUNCTIONAL_SCORES=FUNCTIONAL_SCORES,
            CLINICAL_DATA=CLINICAL_DATA
    }


    output{
        File output_combined_variants_file = merge_variants_clinical.var_clinical_complete    }
}




task merge_variants_clinical {
    input {
        String GENE_NAME
        File VARIANTS_FILE
        File FUNCTIONAL_SCORES
        File CLINICAL_DATA
        Int memSizeGB = 2*round(size(VARIANTS_FILE, "GB") + size(FUNCTIONAL_SCORES, 'GB') + size(CLINICAL_DATA, 'GB')) + 1
        Int threadCount = 1
        Int diskSizeGB = 3*round(size(VARIANTS_FILE, "GB") + size(FUNCTIONAL_SCORES, 'GB') + size(CLINICAL_DATA, 'GB')) + 5

    }

    command <<<
        set -eux -o pipefail

        python3 <<CODE
        import pandas as pd
        import sys

        print("Loading and merging data files...")
        gene_name = "~{GENE_NAME}"

        # Load gnomAD variants
        print(f"Loading gnomAD variants from ~{VARIANTS_FILE}")
        try:
            gnomad_df = pd.read_csv("~{VARIANTS_FILE}")
            print(f"  Loaded {len(gnomad_df)} rows")
            if 'CERFAC_variant_id_VCF_gnomad' in gnomad_df.columns:
                gnomad_df['variant_id'] = gnomad_df['CERFAC_variant_id_VCF_gnomad']
            else:
                print("ERROR: Expected column 'CERFAC_variant_id_VCF_gnomad' not found")
                sys.exit(1)
        except Exception as e:
            print(f"ERROR loading gnomAD: {e}")
            import traceback
            traceback.print_exc()
            sys.exit(1)

        # Load functional scores
        print(f"Loading functional scores from ~{FUNCTIONAL_SCORES}")
        try:
            with open("~{FUNCTIONAL_SCORES}", 'r') as f:
                first_line = f.readline()
                delimiter = '\t' if '\t' in first_line else ','

            scores_df = pd.read_csv("~{FUNCTIONAL_SCORES}", sep=delimiter)
            print(f"  Loaded {len(scores_df)} rows")
            if all(col in scores_df.columns for col in ['chr', 'pos', 'ref', 'alt']):
                scores_df['variant_id'] = (scores_df['chr'].astype(str) + '-' +
                                          scores_df['pos'].astype(str) + '-' +
                                          scores_df['ref'].astype(str) + '-' +
                                          scores_df['alt'].astype(str))
            else:
                print("ERROR: Missing chr/pos/ref/alt columns in functional scores")
                sys.exit(1)
        except Exception as e:
            print(f"ERROR loading functional scores: {e}")
            import traceback
            traceback.print_exc()
            sys.exit(1)

        # Load clinical data
        print(f"Loading clinical data from ~{CLINICAL_DATA}")
        try:
            with open("~{CLINICAL_DATA}", 'r') as f:
                first_line = f.readline()
                delimiter = '\t' if '\t' in first_line else ','

            clinical_df = pd.read_csv("~{CLINICAL_DATA}", sep=delimiter)
            print(f"  Loaded {len(clinical_df)} rows")
            # Clinical data has variant IDs in the second column
            second_col_name = clinical_df.columns[1] if len(clinical_df.columns) > 1 else None
            if second_col_name and second_col_name.strip() in ['hg38', '﻿hg38']:
                clinical_df['variant_id'] = clinical_df[second_col_name].astype(str)
            else:
                print("ERROR: Could not find variant ID column in clinical data")
                sys.exit(1)
        except Exception as e:
            print(f"ERROR loading clinical data: {e}")
            import traceback
            traceback.print_exc()
            sys.exit(1)

        # Merge all data
        print("\nMerging data by variant_id...")
        try:
            merged = pd.merge(scores_df, clinical_df, on='variant_id', how='outer',
                            suffixes=('_scores', '_clinical'))
            print(f"  Scores + clinical: {len(merged)} rows")

            final = pd.merge(gnomad_df, merged, on='variant_id', how='left',
                           suffixes=('_gnomad', ''))
            print(f"  Final with gnomAD: {len(final)} rows")

            output_file = f"{gene_name}_variants_functional_clinical.csv"
            final.to_csv(output_file, index=False)
            print(f"\nMerge complete:")
            print(f"  Output: {output_file}")
            print(f"  Rows: {len(final)}")
            print(f"  Columns: {len(final.columns)}")
        except Exception as e:
            print(f"ERROR during merge: {e}")
            import traceback
            traceback.print_exc()
            sys.exit(1)


        CODE

    >>>

    output {
        File var_clinical_complete = "~{GENE_NAME}_variants_functional_clinical.csv"
    }

    runtime {
        memory: memSizeGB + " GB"
        cpu: threadCount
        disks: "local-disk " + diskSizeGB + " SSD"
        docker: "brcachallenge/cerfac:merge-v1"
        maxRetries: 3
        preemptible: 1
    }
}








